# Generated by Django 4.0.6 on 2022-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_profile_password_journaling_name_profile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
    ]
