# Generated by Django 4.0.6 on 2022-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_journaling_username_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='choices',
        ),
    ]
